from __future__ import annotations

import re

# Standard Protestant canon order (matches urdu-bible-data book IDs 1–66).
ENGLISH_BOOK_IDS: dict[str, int] = {
    "genesis": 1,
    "exodus": 2,
    "leviticus": 3,
    "numbers": 4,
    "deuteronomy": 5,
    "joshua": 6,
    "judges": 7,
    "ruth": 8,
    "1 samuel": 9,
    "2 samuel": 10,
    "1 kings": 11,
    "2 kings": 12,
    "1 chronicles": 13,
    "2 chronicles": 14,
    "ezra": 15,
    "nehemiah": 16,
    "esther": 17,
    "job": 18,
    "psalm": 19,
    "psalms": 19,
    "proverbs": 20,
    "ecclesiastes": 21,
    "song of solomon": 22,
    "song of songs": 22,
    "isaiah": 23,
    "jeremiah": 24,
    "lamentations": 25,
    "ezekiel": 26,
    "daniel": 27,
    "hosea": 28,
    "joel": 29,
    "amos": 30,
    "obadiah": 31,
    "jonah": 32,
    "micah": 33,
    "nahum": 34,
    "habakkuk": 35,
    "zephaniah": 36,
    "haggai": 37,
    "zechariah": 38,
    "malachi": 39,
    "matthew": 40,
    "mark": 41,
    "luke": 42,
    "john": 43,
    "acts": 44,
    "romans": 45,
    "1 corinthians": 46,
    "2 corinthians": 47,
    "galatians": 48,
    "ephesians": 49,
    "philippians": 50,
    "colossians": 51,
    "1 thessalonians": 52,
    "2 thessalonians": 53,
    "1 timothy": 54,
    "2 timothy": 55,
    "titus": 56,
    "philemon": 57,
    "hebrews": 58,
    "james": 59,
    "1 peter": 60,
    "2 peter": 61,
    "1 john": 62,
    "2 john": 63,
    "3 john": 64,
    "jude": 65,
    "revelation": 66,
}

ENGLISH_BOOK_NAMES: dict[int, str] = {
    1: "Genesis",
    2: "Exodus",
    3: "Leviticus",
    4: "Numbers",
    5: "Deuteronomy",
    6: "Joshua",
    7: "Judges",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Kings",
    12: "2 Kings",
    13: "1 Chronicles",
    14: "2 Chronicles",
    15: "Ezra",
    16: "Nehemiah",
    17: "Esther",
    18: "Job",
    19: "Psalms",
    20: "Proverbs",
    21: "Ecclesiastes",
    22: "Song of Solomon",
    23: "Isaiah",
    24: "Jeremiah",
    25: "Lamentations",
    26: "Ezekiel",
    27: "Daniel",
    28: "Hosea",
    29: "Joel",
    30: "Amos",
    31: "Obadiah",
    32: "Jonah",
    33: "Micah",
    34: "Nahum",
    35: "Habakkuk",
    36: "Zephaniah",
    37: "Haggai",
    38: "Zechariah",
    39: "Malachi",
    40: "Matthew",
    41: "Mark",
    42: "Luke",
    43: "John",
    44: "Acts",
    45: "Romans",
    46: "1 Corinthians",
    47: "2 Corinthians",
    48: "Galatians",
    49: "Ephesians",
    50: "Philippians",
    51: "Colossians",
    52: "1 Thessalonians",
    53: "2 Thessalonians",
    54: "1 Timothy",
    55: "2 Timothy",
    56: "Titus",
    57: "Philemon",
    58: "Hebrews",
    59: "James",
    60: "1 Peter",
    61: "2 Peter",
    62: "1 John",
    63: "2 John",
    64: "3 John",
    65: "Jude",
    66: "Revelation",
}


def normalize_book_name(name: str) -> str:
    normalized = name.strip().lower()
    normalized = normalized.replace(".", " ").replace("-", " ")
    normalized = re.sub(r"\s+", " ", normalized)

    roman_prefixes = {
        "i ": "1 ",
        "ii ": "2 ",
        "iii ": "3 ",
        "1st ": "1 ",
        "2nd ": "2 ",
        "3rd ": "3 ",
    }
    for prefix, replacement in roman_prefixes.items():
        if normalized.startswith(prefix):
            normalized = replacement + normalized[len(prefix) :]
            break

    normalized = re.sub(r"^(\d)\s*([a-z])", r"\1 \2", normalized)
    return normalized.strip()


def english_book_to_id(book_name: str) -> int | None:
    return ENGLISH_BOOK_IDS.get(normalize_book_name(book_name))
